name: learninghub_app
description: "Learning Hub App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_launcher_icons: ^0.14.4
  go_router: ^16.2.0
  hooks_riverpod: ^3.0.0-dev.17
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  riverpod_annotation: ^3.0.0-dev.17
  supabase_flutter: ^2.9.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"